/* autogenerated by Processing revision 1303 on 2025-05-02 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.*;
import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Nort extends PApplet {




SoundFile file;
PFont font;
float arenaX;
float arenaY;
float arenaW;
float arenaH;
boolean menu = true;

int round = 0;
int enemyCount;
int allyCount;
Player p1;
Player p2;

// Threads for the game logic
PlayerController p1Controller;
PlayerController p2Controller;
CheckCollision p1Collision;
CheckCollision p2Collision;

int countdownTime = 3;
int startTime;
boolean roundStarted = false;

float healthMenuY;
float healthMenuX;

public void setup(){
  /* size commented out by preprocessor */;
  background(0);
  frameRate(60);
  arenaX = width/8;
  arenaY = height/8-100;
  arenaW = width/8*6;
  arenaH = height/8*6-100;
  healthMenuY = height/8*6;
  healthMenuX = width/10*3;
  
  font = createFont("dogica.ttf", 32);
  textFont(font);
  
  file = new SoundFile(this, "asc-binary.mp3");
  file.loop();

  p1 = new Player(arenaX + arenaW/3, height/2, true);
  p2 = new Player(arenaX + arenaW/3*2, height/2, false);
  
  // Initialize and start controllers and collision checkers
  p1Controller = new PlayerController(p1, true);
  p2Controller = new PlayerController(p2, false);
  p1Collision = new CheckCollision(p1, p2);
  p2Collision = new CheckCollision(p2, p1);
  p1Controller.start();
  p2Controller.start();
  p1Collision.start();
  p2Collision.start();
}

public void keyPressed(){
  if (key ==  'a' || key == 'w' || key == 'd'){
    p1Controller.setKey(key);
  }
  if (key == CODED){
    p2Controller.setArrowKey(keyCode);
  }
}

public void draw(){
  // Count Down
  background(0);
  if (menu){
    textAlign(CENTER);
    text("Press S to start the game", width/2, height/3);
    text("Player 1 uses W, A, D to move", width/2, height/2);
    text("Player 2 uses arrow keys to move", width/2, height/2 + 50);
    if (keyPressed){
      if (key == 's'){menu = false;}
      startTime = millis();
    }
  } else {
    if (!roundStarted){
      int elapsedTime = (millis() - startTime) / 1000;  // Convert to seconds
      int remainingTime = countdownTime - elapsedTime;  // Countdown
      
      if (remainingTime > 0) {
        // Show countdown on screen
        fill(255);
        textSize(50);
        textAlign(CENTER, CENTER);
        text(remainingTime, width / 2, height / 2);
        return; 
      } else { roundStarted = true; }
    }
    // Game Over Menu
    if (p1.health == 0 || p2.health == 0){
      textSize(40);
      if (p1.health == 0){
        textAlign(CENTER);
        fill(p2.c);
        text("PLAYER 2 WINS!", width/2, height/2);
      } else {
        textAlign(CENTER);
        fill(p1.c);
        text("PLAYER 1 WINS!", width/2, height/2);
      }
      textSize(20);
      text("Press R to restart!", width/2, height/3*2);
      if (keyPressed){
        if (key == 'r'){
          p1 = new Player(arenaX + arenaW/3, height/2, true);
          p2 = new Player(arenaX + arenaW/3*2, height/2, false);
          p1Controller.player = p1;
          p2Controller.player = p2;
          p1Collision.player = p1;
          p1Collision.enemy = p2;
          p2Collision.player = p2;
          p2Collision.enemy = p1;
          roundStarted = false;
          startTime = millis();
        }
      }
    // Main Game Play
    } else {
      float elapsedTime = (millis() - startTime) / 1000;
      if (elapsedTime > 15){
        startSuddenDeath(elapsedTime);
      }
      stroke(255);
      noFill();
      rectMode(CORNER);
      rect(arenaX, arenaY, arenaW, arenaH);
      pushMatrix();
        translate(healthMenuX, healthMenuY);
        textAlign(RIGHT);
        textSize(40);
        fill(p1.c);
        text("P1:", 40, 40);
        noStroke();
        textAlign(LEFT);
        text("Use W, A, D to control", 400, 40);
        for (int i=0; i<p1.health; i++){
          rect(50 + i*50, 0, 30, 60);
        }
        translate(0, 90);
        fill(p2.c);
        textAlign(RIGHT);
        text("P2:", 40, 40);
        textAlign(LEFT);
        text("Use UP, LEFT, RIGHT to control", 400, 40);
        for (int i=0; i<p2.health; i++){
          rect(50 + i*50, 0, 30, 60);
        }
      popMatrix();
      p1.draw();
      p2.draw();
    }
  }   
}

public void startSuddenDeath(float elapsedTime){
  if (elapsedTime < 22){
    arenaX +=1.5f;
    arenaW -=3;
  }
}

public void resetRound(){
  roundStarted = false;
  startTime = millis();
  
  // Reset player positions and angles
  p1.playerReset();
  p2.playerReset();
  // Reset controller states to neutral/forward
  p1Controller.currentKey = 'w';
  p2Controller.currentArrowKey = UP;
  
  // Reset arena dimensions
  arenaX = width/8;
  arenaY = height/8-100;
  arenaW = width/8*6;
  arenaH = height/8*6-100;
}

public void stop() {
  p1Controller.stopController();
  p2Controller.stopController();
  p1Collision.stopCheckCollision();
  p2Collision.stopCheckCollision();
  super.stop();
}
public class CheckCollision extends Thread {
  Player player, enemy;
  volatile boolean running = true;
  
  CheckCollision(Player player, Player enemy) {
    this.player = player;
    this.enemy = enemy;
  }

  public void run() {
    while (running) {
      // Only check collisions if the player is alive
      if (player.health > 0) {
        player.checkTouchOwn();
        player.checkBoundaries();
        player.checkTouchOther(enemy);
      }
      
      try {
        Thread.sleep(10); // Add a small delay so that it doesn't eat up CPU time
      } catch (InterruptedException e) {
        // Handle interruption gracefully
        running = false;
      }
    }
  }

  public void stopCheckCollision() {
    running = false;
    interrupt(); // Ensure the thread exits cleanly
  }
}
class Player {
  float x, y;
  float front = 30;
  float side = 56;
  int health = 5;
  float speed = 6;
  float angle = PI+HALF_PI;  // Angle in radians
  float turnSpeed = 0.07f;  // Adjusted turn speed for better control
  char motion;
  int arrowKeys;
  boolean playerOne;
  int c;
  PImage img;
  //the trail attributes
  ArrayList<Segment> body;
  int len = 20;
  float r = 18; //distance between each trail segment

  public Player(float x, float y, boolean playerOne) {
    this.x = x;
    this.y = y;
    this.playerOne = playerOne;
    if (playerOne){
      img = loadImage("p1Bike.png");
      c = color(209,224,0,255);
    }else{
      img = loadImage("p2Bike.png");
      c = color(224,0,66,225);
    }
    body = new ArrayList<Segment>();
    for(int i=0; i<len; i++){
      body.add(new Segment(x, y + r*i, angle, r, r,c));
    }
  }

  public Player(float x, float y, boolean playerOne, int health) {
    this.x = x;
    this.y = y;
    this.health = health;
    this.playerOne = playerOne;
    if (playerOne){
      c = color(209,224,0,255);
    }else{
      c = color(224,0,66,225);
    }
    body = new ArrayList<Segment>();
    for(int i=0; i<len; i++){
      body.add(new Segment(x, y + r*i, angle, r, r,c));
    }
  }

  public void draw() {
    pushMatrix();
    translate(x, y);
    rotate(angle);  
    fill(52, 119, 235);
    imageMode(CENTER);
   
    rotate(HALF_PI);
    image(img, 0, 0, front, side);
    popMatrix();
    x += speed * cos(angle);
    y += speed * sin(angle);
    
    update();
    drawTrail();
  }

  public void checkBoundaries() {
    float halfSide = side / 2;
    float halfFront = front / 2;

    // Prevent going beyond left boundary
    if (x - halfSide < arenaX) {
      x = arenaX + halfSide;
    }

    // Prevent going beyond right boundary
    if (x + halfSide > arenaX + arenaW) {
      x = arenaX + arenaW - halfSide;
    }

    // Prevent going beyond top boundary
    if (y - halfFront < arenaY) {
      y = arenaY + halfFront;
    }

    // Prevent going beyond bottom boundary
    if (y + halfFront > arenaY + arenaH) {
      y = arenaY + arenaH - halfFront;
    }
  }



  // touch own line
  public void checkTouchOwn(){
    for (int i=3; i<len; i++){
      Segment s = body.get(i);
      float d = dist(x,y,s.x,s.y);

      if (d < r/2) {
        health--;
        if (health > 0){
          resetRound();
        }
      }
    }
  }

  public void checkTouchOther(Player enemy){
    for (int i=1; i<len; i++){
      Segment s = enemy.body.get(i);
      float d = dist(x,y,s.x,s.y);

      if (d < r/2) {
        health--;
        if (health > 0){
          resetRound();
        }
      }
    }
  }

  // update the trail 
  public void update(){
    Segment head = body.get(0);
    float a = atan2(y - head.y, x - head.x);
    head.angle = a;
    head.x += speed * cos(head.angle);
    head.y += speed * sin(head.angle);
    head.c = color(0,0,0,0);
    for (int i=1; i<len; i++){
      Segment c = body.get(i);
      Segment p = body.get(i-1);
      c.update(p);
    }
  }

  public void drawTrail(){
    for (int i=0; i<len; i++){
      body.get(i).display();
    }
  }

  public void playerReset(){
    if (playerOne){
      x = arenaX + 60;
      y = height/2;
    }else{
      x = arenaX + arenaW - 60;
      y = height/2;
    }
    angle = HALF_PI + PI;
    body = new ArrayList<Segment>();
    for(int i=0; i<len; i++){
      body.add(new Segment(x, y + r*i, angle, r, r,c));
    }
  }
}
public class PlayerController extends Thread {
  Player player;
  volatile boolean running = true;
  volatile char currentKey = 0;
  volatile int currentArrowKey = 0;
  boolean isPlayerOne;

  PlayerController(Player player, boolean isPlayerOne) {
    this.player = player;
    this.isPlayerOne = isPlayerOne;
  }

  public void run() {
    while (running) {
      if (roundStarted){
        if (isPlayerOne) {
          if (currentKey == 'a' || currentKey == 'd' || currentKey == 'w') {
              switch(currentKey){
                  case 'a':
                      player.angle -= player.turnSpeed;  // Turn left (counterclockwise)
                      break;
                  case 'd':
                      player.angle += player.turnSpeed;  // Turn left (counterclockwise)
                      break;
              }
          }
        } else {
          if (currentArrowKey == LEFT || currentArrowKey == RIGHT || currentArrowKey == UP) {
              switch(currentArrowKey){
                  case LEFT:
                      player.angle -= player.turnSpeed;  // Turn left (counterclockwise)
                      break;
                  case RIGHT:
                      player.angle += player.turnSpeed;  // Turn left (counterclockwise)
                      break;
              }
          }
        }
        try {
          Thread.sleep(16); // Sleep 60 FPS so that it doesn't eat up CPU time
        } catch (InterruptedException e) {
          e.printStackTrace();
          running = false;
        }
      }
    }
  }

  public void setKey(char k) {
    currentKey = k;
  }

  public void setArrowKey(int k) {
    currentArrowKey = k;
  }

  public void stopController() {
    running = false;
    interrupt();
  }
}
class Segment {
  float x, y;
  float angle;
  float distance;
  float radius;
  int c;
  
  Segment(float x, float y, float a, float d, float r, int c){
    this.x = x;
    this.y = y;
    angle = a;
    distance = d;
    radius = r;
    this.c = c;
  }

  public void update(Segment prev){
    float a = atan2(prev.y-y, prev.x-x);
    angle = a;
    float d = sqrt(pow(prev.x-x,2) + pow(prev.y-y,2));
    if (d > distance){
      float delta = d - distance;
      x+= delta*cos(angle);
      y+= delta*sin(angle);
    }
  }

  public void display(){
    pushMatrix();
      translate(x,y);
      rotate(angle);
      stroke(c);
      line(0,0,distance,0);
    popMatrix();
  }
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "Nort" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
